name: Build Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: spectado/spectado-hls-relay
  IMAGE_TAG: ${{ env.PACKAGE_VERSION }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get package version
        run: echo "::set-env name=PACKAGE_VERSION::$(cat package.json | jq -r '.version')"

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
